# g:\cyberlearn\labs\sqli-blind\Dockerfile

# Используем официальный образ PHP с Apache
FROM php:8.0-apache

# Копируем файлы лабы внутрь контейнера
COPY . /var/www/html/

# Открываем 80 порт (внутри контейнера)
EXPOSE 80
