FROM node:18-alpine
WORKDIR /var/www/html
RUN echo "flag{dummy}" > /flag.txt
# Устанавливаем express и nunjucks
RUN npm init -y && npm install express nunjucks
COPY . .
EXPOSE 80
CMD ["node", "app.js"]
