FROM php:8.2-apache

# Ставим SQLite3 и расширение PDO для PHP
RUN apt-get update && apt-get install -y sqlite3 libsqlite3-dev \
   && docker-php-ext-install pdo pdo_sqlite

COPY ./index.php /var/www/html/index.php

RUN chown -R www-data:www-data /var/www/html/